config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end
  
  root to: 'bbs#index'
  resources :bbs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bb.rb
class Bb < ApplicationRecord
	has_one_attached :image
	before_validation :set_nameless_name
	validates :name, presence: true, length: { maximum: 30 }
	validate :validates_name_not_including_comma

	private

	def set_nameless_name
		self.name = '名前なし' if name.blank?
	end

	def validates_name_not_including_comma
		errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
	end
	belongs_to :user

	scope :recent, -> {order(created_at: :desc)}
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, prosence: true, length: {maximum:255}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
	validates :message, prosence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true

	has_many :bbs
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}を登録しました。」"
  	else
  		render :new
  	end
  end

  def update
  	@user = User.find(params[:id])

  	if @user.update(user_params)
  		redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
  	else
  		render :edit
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to admin_user_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
  	redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	before_action :login_required

	private

	def current_user
		@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
	end	

	def login_required
		redirect_to login_url unless current_user
	end
end

app/controllers/bbs_controller.rb
class BbsController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @bbs = current_user.bbs.order(created_at: :desc)
  end

  def show
    @bbs = Bb.find(params[:id])
  end

  def new
  	@bbs = Bb.new
  end

  def create
    @bbs = Bb.new(bbs_params.merge(user_id: current_user.id))
  	
  	if @bbs.save
      redirect_to @bbs, notice: "掲示板「#{@bbs.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @bbs = current_user.bbs.find(params[:id])
  end

  def update
    bbs = current_user.bbs.find(params[:id])
    bbs.update!(bbs_params)
    redirect_to bbs_url, notice: "掲示板「#{@bbs.name}」を更新しました。"
  end

  def destroy
    bbs = current_user.bbs.find(params[:id])
    bbs.destroy
    redirect_to bbs_url, notice: "掲示板「#{@bbs.name}」を削除しました。"
  end

  private

  def bbs_params
  	params.require(:bb).permit(:name, :description, :image)
  end

  def set_task
    @task = current_user.bbs.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :login_required
  def new
  end

  def create
  	user = User.find_by(email: session_params[:email])

  	if user&.authenticate(session_params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: 'ログインしました'
  	else
  		render :new
  	end
  end

def destroy
	reset_session
	redirect_to root_url, notice: 'ログアウトしました。'
end

private
	def session_params
		params.require(:session).permit(:email, :password)
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_helper.rb
module BbsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
	ul#error_explanation
		- user.errors.full_messages.each do |message|
			li= message


= form_with model: [:admin, user], local: true do |f|
	.form-group
		= f.label :name, '名前'
		= f.text_field :name, class: 'form-control'
	.form-group
		= f.label :email, 'メールアドレス'
		= f.text_field :email, class: 'form-control'
	.form-check
		= f.label :admin, class: 'form-check-label' do
			=f.check_box :admin, class: 'form-check-input'
			| 管理者権限
	.form-group
		= f.label :password, 'パスワード'
		= f.password_field :password, class: 'form-control'
	.form-group
		= f.label :password_confirmation, 'パスワード（確認）'
		= f.password_field :password_confirmation, class: 'form-control'
	= f.submit '登録する', class:'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
	= link_to '一覧', admin_users_path, class: 'nav-link'
= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mp-3
table.table.table-hover
	thead.thead-default
		tr
			th= User.human_attribute_name(:name)
			th= User.human_attribute_name(:email)
			th= User.human_attribute_name(:admin)
			th= User.human_attribute_name(:created_at)
			th= User.human_attribute_name(:updated_at)
			th
	tbody
		- @users.each do |user|
			tr
				td= link_to user.name, [:admin, user]
				td= user.email
				td= user.admin? ? 'あり' : 'なし'
				td= user.created_at
				td= user.updated_at
				td
					= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
					= link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
	= link_to '一覧', admin_users_path, class: 'nav-link'
= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
	=link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
	tbody
		tr
			th= User.human_attribute_name(:id)
			td= @user.id
		tr
			th= User.human_attribute_name(:name)
			td= @user.name
		tr
			th= User.human_attribute_name(:email)
			td= @user.email
		tr
			th= User.human_attribute_name(:admin)
			td= @user.admin? ? 'あり' : 'なし'
		tr
			th= User.human_attribute_name(:created_at)
			td= @user.created_at
		tr
			th= Bb.human_attribute_name(:updated_at)
			td= @user.updated_at
			
= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいいですか？" }, class: 'btn btn-danger'

app/views/bbs/_form.html.slim
- if bb.errors.present?
	ul#error_explanation
		- bb.errors.full_messages.each do |message|
			li= message

= form_with model: bb, local: true do |f|
	.form-group
		= f.label :name
		= f.text_field :name, class: 'form-control', id: 'bbs_name'
	.form-group
		= f.label :description
		= f.text_area :description, rows: 5, class: 'form-control', id: 'bbs_description'
	.form-group
		= f.label :image
		= f.file_field :image, class: 'form-control'
	= f.submit nil, class: 'btn btn-primary'

app/views/bbs/edit.html.slim
h1 掲示板の編集

nav.justify-content-end
 = link_to '一覧', bbs_path, class: 'nav-link'

= render partial: 'form', locals: { bb: @bb }

app/views/bbs/index.html.slim
h1 掲示板

= link_to '新規登録', new_bb_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
 thread.thread-default
  tr
  	th= @bbs.human_attribute_name(:name)
  	th= @bbs.human_attribute_name(:created_at)
  	th
  tbody
   - @bbs.each do |bb|
   	tr
   		td= link_to bb.name, bb
   		td= bb.created_at
   		td
   			= link_to '編集', edit_bb_path(bb), class: 'btn btn-primary mr-3'
   			= link_to '削除', bb, method: :delete, data: {confirm: "掲示板「#{bb.name}」を削除します。よろしいいですか？"}, class: 'btn btn-danger'

app/views/bbs/new.html.slim
h1 掲示板の新規登録

.nav.justify-content-end
	= link_to '一覧', bbs_path, class: 'nav-link'

= render partial: 'form', locals: { bb: @bbs }

app/views/bbs/show.html.slim
h1 掲示板詳細

.nav.justify-content-end
	=link_to '一覧', bbs_path, class: 'nav-link'
table.table.table-hover
	tbody
		tr
			th= Bb.human_attribute_name(:id)
			td= @bbs.id 
		tr
			th= Bb.human_attribute_name(:name)
			td= @bbs.name
		tr
			th= Bb.human_attribute_name(:description)
			td= simple_format(h(@bbs.description), {}, sanitize: false, wrapper_tag: "div")
		tr
			th= Bb.human_attribute_name(:image)
			td= image_tag @bbs.image if @bbs.image.attached?
		tr
			th= Bb.human_attribute_name(:created_at)
			td= @bbs.created_at
		tr
			th= Bb.human_attribute_name(:updated_at)
			td= @bbs.updated_at
			
= link_to '編集', edit_bb_path, class: 'btn btn-primary mr-3'
= link_to '削除', @bbs, method: :delete, data: {confirm: "掲示板「#{@bbs.name}」を削除します。よろしいいですか？"}, class: 'btn btn-danger'

app/views/contacts/create.html.slim
h1 Contacts#create
p Find me in app/views/contacts/create.html.slim

app/views/contacts/new.html.slim
h1 Contacts#new
p Find me in app/views/contacts/new.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Bbs
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
  	.app-title.navbar.navbar-expand-md.navbar-light.bg-light
  		.navbar-brand Bbs

    ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to '掲示板一覧', bbs_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
  	.container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    = yield